# Copyright (c) 2024 - 2025 Narcis Mestres 

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project Information
site_name: "404 Thoughts"
site_author: Nacis Mestres
site_url: https://nar6mes3.github.io/blog/
site_description: >-
  A place to dump technical solutions, thoughts and experiments


# Repository
repo_name: Nar6mes3/blog
repo_url: https://github.com/nar6mes3/blog

# Copyright
copyright: Copyright &copy; 2024-2025 Narcis Mestres

theme:
  name: material
  logo: assets/logo_brain_only-transparent.png            # Logo path
  favicon: assets/favicon.ico     
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.section
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - tags

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      custom_dir: overrides

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: 'black'
      accent: 'silver'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - About Me: about.md
  - Blog: 
      - blog/index.md
      - tags.md

plugins:
  - blog:
      draft_on_serve: true
  - search
  - social
  - tags:
      enabled: true
      tags: true
      tags_file: tags.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  tags:
    tags: true
    enabled: true
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/nar6mes3
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/narcis-mestres/
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.