authors:
  narcis:
    name: Narcis Mestres        # Author name
    description: Creator # Author description
    avatar: "assets/narcis_comic_book.png"         # Author avatar
    slug: https://nar6mes3.github.io/blog/about           # Author profile slug
    url: https://nar6mes3.github.io/blog/            # Author website URL